name: Deploy HTML to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: unbuntu-latest
    
    steps:
      - name: checkout code
        used: actions/checkout@v4
      - name: show all files
        run: ls -al

        - name: doing SSH to Ec2
      
